pub mod admin;
pub mod claim;
pub mod fund;
pub mod initialize;
pub mod reward;
pub mod stake;
pub mod token_ext;
pub mod unstake;

#[cfg(feature = "devnet-faucet")]
pub mod faucet;

// Glob re-export is REQUIRED: it also brings in the hidden `__client_accounts_*`
// modules generated by #[derive(Accounts)], which the #[program] macro needs.
// (The benign `ambiguous glob re-exports` warning on `handler` is expected — lib.rs
// calls handlers by full path, e.g. instructions::stake::handler.)
pub use admin::*;
pub use claim::*;
pub use fund::*;
pub use initialize::*;
pub use stake::*;
pub use unstake::*;

#[cfg(feature = "devnet-faucet")]
pub use faucet::*;
