pub mod admin;
pub mod claim;
pub mod close_user;
pub mod create_pool;
pub mod fund;
pub mod hook;
pub mod initialize;
pub mod register;
pub mod reward;
pub mod stake;
pub mod token_ext;
pub mod unstake;

#[cfg(feature = "devnet-faucet")]
pub mod faucet;

// Glob re-export is REQUIRED: it also brings in the hidden `__client_accounts_*`
// modules generated by #[derive(Accounts)], which the #[program] macro needs.
pub use admin::*;
pub use claim::*;
pub use close_user::*;
pub use create_pool::*;
pub use fund::*;
pub use hook::*;
pub use initialize::*;
pub use register::*;
pub use stake::*;
pub use unstake::*;

#[cfg(feature = "devnet-faucet")]
pub use faucet::*;
